2022-11-22T17:05:53.3410880+08:00|1|INFO|DataSync.Log|Storage folder: /Users/kangkang/kypkk_pico/Assets/TestData/TestStore successfully validated. 
2022-11-22T17:05:53.3694480+08:00|474|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-11-22T17:05:53.4265700+08:00|474|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-11-22T17:05:53.4784590+08:00|474|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-11-22T17:05:53.5352290+08:00|474|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-11-22T17:06:23.3978510+08:00|464|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-11-22T17:06:23.5126170+08:00|464|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b27b6fbe7e17405ba6693fe69c2d14cc(0-0). 
2022-11-22T17:06:23.5218470+08:00|464|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b27b6fbe7e17405ba6693fe69c2d14cc(0-0). 
2022-11-22T17:07:39.7241020+08:00|481|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b27b6fbe7e17405ba6693fe69c2d14cc(0-0). Message: System.Net.WebException: Error: ConnectFailure (Connection timed out) ---> System.Net.Sockets.SocketException: Connection timed out   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Net.Sockets.SocketTaskExtensions+<>c.<ConnectAsync>b__2_1 (System.IAsyncResult asyncResult) [0x00006] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <695d1cc93cca45069c528c15c9fdd749>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x0019b] in <39d8670c8f6e487fb992d3c14d754584>:0     --- End of inner exception stack trace ---   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00217] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebOperation+<Run>d__54.MoveNext () [0x000a0] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0001d] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <695d1cc93cca45069c528c15c9fdd749>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-11-22T17:07:39.7362650+08:00|481|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b27b6fbe7e17405ba6693fe69c2d14cc(0-0). Message: Error: ConnectFailure (Connection timed out). StatusCode: 0. Description: . 
2022-11-23T13:47:02.5891780+08:00|1|INFO|DataSync.Log|Storage folder: /Users/kangkang/kypkk_pico/Assets/TestData/TestStore successfully validated. 
2022-11-23T13:47:02.6190550+08:00|19|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-11-23T13:47:02.6738180+08:00|19|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-11-23T13:47:02.7376750+08:00|19|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-11-23T13:47:02.7923890+08:00|19|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-11-23T13:47:32.6456830+08:00|19|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-11-23T13:47:32.7867450+08:00|19|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: e1efcdd673c3499e921fa4d18881b2c2(0-0). 
2022-11-23T13:47:32.7912910+08:00|19|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: e1efcdd673c3499e921fa4d18881b2c2(0-0). 
2022-11-23T13:48:48.0939670+08:00|37|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e1efcdd673c3499e921fa4d18881b2c2(0-0). Message: System.Net.WebException: Error: ConnectFailure (Connection timed out) ---> System.Net.Sockets.SocketException: Connection timed out   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Net.Sockets.SocketTaskExtensions+<>c.<ConnectAsync>b__2_1 (System.IAsyncResult asyncResult) [0x00006] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <695d1cc93cca45069c528c15c9fdd749>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x0019b] in <39d8670c8f6e487fb992d3c14d754584>:0     --- End of inner exception stack trace ---   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00217] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebOperation+<Run>d__54.MoveNext () [0x000a0] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0001d] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <695d1cc93cca45069c528c15c9fdd749>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-11-23T13:48:48.1003280+08:00|37|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e1efcdd673c3499e921fa4d18881b2c2(0-0). Message: Error: ConnectFailure (Connection timed out). StatusCode: 0. Description: . 
2022-11-23T13:49:51.4690930+08:00|1|INFO|DataSync.Log|Storage folder: /Users/kangkang/kypkk_pico/Assets/TestData/TestStore successfully validated. 
2022-11-23T13:49:51.4926300+08:00|36|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-11-23T13:49:51.5460740+08:00|36|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-11-23T13:49:51.5975060+08:00|36|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-11-23T13:49:51.6498770+08:00|36|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-11-23T13:50:21.5030110+08:00|40|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-11-23T13:50:21.5649280+08:00|40|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 0050865cae884863bf2fde57ca8a4a1b(0-0). 
2022-11-23T13:50:21.5672080+08:00|40|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 0050865cae884863bf2fde57ca8a4a1b(0-0). 
2022-11-23T13:51:36.6951220+08:00|53|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 0050865cae884863bf2fde57ca8a4a1b(0-0). Message: System.Net.WebException: Error: ConnectFailure (Connection timed out) ---> System.Net.Sockets.SocketException: Connection timed out   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Net.Sockets.SocketTaskExtensions+<>c.<ConnectAsync>b__2_1 (System.IAsyncResult asyncResult) [0x00006] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <695d1cc93cca45069c528c15c9fdd749>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x0019b] in <39d8670c8f6e487fb992d3c14d754584>:0     --- End of inner exception stack trace ---   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00217] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Net.WebOperation+<Run>d__54.MoveNext () [0x000a0] in <39d8670c8f6e487fb992d3c14d754584>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0001d] in <39d8670c8f6e487fb992d3c14d754584>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <695d1cc93cca45069c528c15c9fdd749>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-11-23T13:51:36.7011730+08:00|53|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 0050865cae884863bf2fde57ca8a4a1b(0-0). Message: Error: ConnectFailure (Connection timed out). StatusCode: 0. Description: . 
2022-11-23T14:28:22.6997220+08:00|1|INFO|DataSync.Log|Storage folder: /Users/kangkang/kypkk_pico/Assets/TestData/TestStore successfully validated. 
2022-11-23T14:28:22.7252230+08:00|77|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-11-23T14:28:22.7794170+08:00|77|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-11-23T14:28:22.8313970+08:00|77|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-11-23T14:28:22.8936850+08:00|77|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-11-23T14:28:52.7410750+08:00|76|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-11-23T14:28:52.8486540+08:00|76|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 1903c3e0ad3c41139c2614e1f40c9184(0-0). 
2022-11-23T14:28:52.8512870+08:00|76|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 1903c3e0ad3c41139c2614e1f40c9184(0-0). 
2022-11-23T14:31:54.8357990+08:00|1|INFO|DataSync.Log|Storage folder: /Users/kangkang/kypkk_pico/Assets/TestData/TestStore successfully validated. 
2022-11-23T14:31:54.8675120+08:00|91|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-11-23T14:31:54.9222310+08:00|91|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-11-23T14:31:54.9742400+08:00|91|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-11-23T14:31:55.0267230+08:00|91|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-11-23T14:34:49.2053450+08:00|1|INFO|DataSync.Log|Storage folder: /Users/kangkang/kypkk_pico/Assets/TestData/TestStore successfully validated. 
2022-11-23T14:34:49.2304600+08:00|19|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-11-23T14:34:49.2879580+08:00|19|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-11-23T14:34:49.3392040+08:00|19|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-11-23T14:34:49.3925030+08:00|19|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-11-23T14:35:19.2488540+08:00|27|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-11-23T14:35:19.3174800+08:00|27|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: dd4c46929f184ff6b2ecc1285e82d5fd(0-0). 
2022-11-23T14:35:19.3227560+08:00|27|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: dd4c46929f184ff6b2ecc1285e82d5fd(0-0). 
